---
name: Crypt-Nash
version: 0.1
author: []
abstract: Implementation of Nash Cryptosystem
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
provides:
  Crypt::Nash:
    file: lib/Crypt/Nash.pm
    version: 0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
